swagger: "2.0"
info: {}
paths: {}
definitions:
  models.BlogEntry:
    title: BlogEntry
    type: object
    properties:
      Body:
        type: string
      CreatedBy:
        type: string
      CreatedOn:
        type: string
      Id:
        type: integer
        format: int64
      ModifiedBy:
        type: string
      ModifiedOn:
        type: string
      Slug:
        type: string
      Status:
        type: string
      Tags:
        type: string
      Title:
        type: string
  models.Resource:
    title: Resource
    type: object
